apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: myweb
    app.kubernetes.io/instance: mylwapp
  name: myweb
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: myweb
  type: NodePort
status:
  loadBalancer: {}
